// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: lib/proto/gzset/db.proto

package gzset

import (
	any1 "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ZSetValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score  int32     `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Member string    `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	Value  *any1.Any `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ZSetValue) Reset() {
	*x = ZSetValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZSetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZSetValue) ProtoMessage() {}

func (x *ZSetValue) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZSetValue.ProtoReflect.Descriptor instead.
func (*ZSetValue) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{0}
}

func (x *ZSetValue) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ZSetValue) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *ZSetValue) GetValue() *any1.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type ZAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Member *ZSetValue `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *ZAddRequest) Reset() {
	*x = ZAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZAddRequest) ProtoMessage() {}

func (x *ZAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZAddRequest.ProtoReflect.Descriptor instead.
func (*ZAddRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{1}
}

func (x *ZAddRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ZAddRequest) GetMember() *ZSetValue {
	if x != nil {
		return x.Member
	}
	return nil
}

type ZAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ZAddResponse) Reset() {
	*x = ZAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZAddResponse) ProtoMessage() {}

func (x *ZAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZAddResponse.ProtoReflect.Descriptor instead.
func (*ZAddResponse) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{2}
}

func (x *ZAddResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ZAddResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ZAddsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string       `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Members []*ZSetValue `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *ZAddsRequest) Reset() {
	*x = ZAddsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZAddsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZAddsRequest) ProtoMessage() {}

func (x *ZAddsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZAddsRequest.ProtoReflect.Descriptor instead.
func (*ZAddsRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{3}
}

func (x *ZAddsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ZAddsRequest) GetMembers() []*ZSetValue {
	if x != nil {
		return x.Members
	}
	return nil
}

type ZAddsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ZAddsResponse) Reset() {
	*x = ZAddsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZAddsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZAddsResponse) ProtoMessage() {}

func (x *ZAddsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZAddsResponse.ProtoReflect.Descriptor instead.
func (*ZAddsResponse) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{4}
}

func (x *ZAddsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ZAddsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ZRemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Member string `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *ZRemRequest) Reset() {
	*x = ZRemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRemRequest) ProtoMessage() {}

func (x *ZRemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRemRequest.ProtoReflect.Descriptor instead.
func (*ZRemRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{5}
}

func (x *ZRemRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ZRemRequest) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

type ZRemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ZRemResponse) Reset() {
	*x = ZRemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRemResponse) ProtoMessage() {}

func (x *ZRemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRemResponse.ProtoReflect.Descriptor instead.
func (*ZRemResponse) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{6}
}

func (x *ZRemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ZRemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ZRemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Members []string `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *ZRemsRequest) Reset() {
	*x = ZRemsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRemsRequest) ProtoMessage() {}

func (x *ZRemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRemsRequest.ProtoReflect.Descriptor instead.
func (*ZRemsRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{7}
}

func (x *ZRemsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ZRemsRequest) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type ZRemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ZRemsResponse) Reset() {
	*x = ZRemsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRemsResponse) ProtoMessage() {}

func (x *ZRemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRemsResponse.ProtoReflect.Descriptor instead.
func (*ZRemsResponse) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{8}
}

func (x *ZRemsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ZRemsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ZScoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Member string `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *ZScoreRequest) Reset() {
	*x = ZScoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZScoreRequest) ProtoMessage() {}

func (x *ZScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZScoreRequest.ProtoReflect.Descriptor instead.
func (*ZScoreRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{9}
}

func (x *ZScoreRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ZScoreRequest) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

type ZScoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score  int32 `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Exists bool  `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *ZScoreResponse) Reset() {
	*x = ZScoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZScoreResponse) ProtoMessage() {}

func (x *ZScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZScoreResponse.ProtoReflect.Descriptor instead.
func (*ZScoreResponse) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{10}
}

func (x *ZScoreResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ZScoreResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type ZRankRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Member string `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *ZRankRequest) Reset() {
	*x = ZRankRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRankRequest) ProtoMessage() {}

func (x *ZRankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRankRequest.ProtoReflect.Descriptor instead.
func (*ZRankRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{11}
}

func (x *ZRankRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ZRankRequest) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

type ZRankResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rank   int32 `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Exists bool  `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *ZRankResponse) Reset() {
	*x = ZRankResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRankResponse) ProtoMessage() {}

func (x *ZRankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRankResponse.ProtoReflect.Descriptor instead.
func (*ZRankResponse) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{12}
}

func (x *ZRankResponse) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *ZRankResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type ZRevRankRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Member string `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *ZRevRankRequest) Reset() {
	*x = ZRevRankRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRevRankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRevRankRequest) ProtoMessage() {}

func (x *ZRevRankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRevRankRequest.ProtoReflect.Descriptor instead.
func (*ZRevRankRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{13}
}

func (x *ZRevRankRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ZRevRankRequest) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

type ZRevRankResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rank   int32 `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Exists bool  `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *ZRevRankResponse) Reset() {
	*x = ZRevRankResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRevRankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRevRankResponse) ProtoMessage() {}

func (x *ZRevRankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRevRankResponse.ProtoReflect.Descriptor instead.
func (*ZRevRankResponse) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{14}
}

func (x *ZRevRankResponse) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *ZRevRankResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type ZRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Start int32  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End   int32  `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *ZRangeRequest) Reset() {
	*x = ZRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRangeRequest) ProtoMessage() {}

func (x *ZRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRangeRequest.ProtoReflect.Descriptor instead.
func (*ZRangeRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{15}
}

func (x *ZRangeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ZRangeRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ZRangeRequest) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

type ZRangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members []*ZSetValue `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *ZRangeResponse) Reset() {
	*x = ZRangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRangeResponse) ProtoMessage() {}

func (x *ZRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRangeResponse.ProtoReflect.Descriptor instead.
func (*ZRangeResponse) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{16}
}

func (x *ZRangeResponse) GetMembers() []*ZSetValue {
	if x != nil {
		return x.Members
	}
	return nil
}

type ZCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Min int32  `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	Max int32  `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *ZCountRequest) Reset() {
	*x = ZCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZCountRequest) ProtoMessage() {}

func (x *ZCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZCountRequest.ProtoReflect.Descriptor instead.
func (*ZCountRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{17}
}

func (x *ZCountRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ZCountRequest) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *ZCountRequest) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type ZCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ZCountResponse) Reset() {
	*x = ZCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZCountResponse) ProtoMessage() {}

func (x *ZCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZCountResponse.ProtoReflect.Descriptor instead.
func (*ZCountResponse) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{18}
}

func (x *ZCountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ZRevRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	StartRank int32  `protobuf:"varint,2,opt,name=startRank,proto3" json:"startRank,omitempty"`
	EndRank   int32  `protobuf:"varint,3,opt,name=endRank,proto3" json:"endRank,omitempty"`
}

func (x *ZRevRangeRequest) Reset() {
	*x = ZRevRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRevRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRevRangeRequest) ProtoMessage() {}

func (x *ZRevRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRevRangeRequest.ProtoReflect.Descriptor instead.
func (*ZRevRangeRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{19}
}

func (x *ZRevRangeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ZRevRangeRequest) GetStartRank() int32 {
	if x != nil {
		return x.StartRank
	}
	return 0
}

func (x *ZRevRangeRequest) GetEndRank() int32 {
	if x != nil {
		return x.EndRank
	}
	return 0
}

type ZRevRangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members []*ZSetValue `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *ZRevRangeResponse) Reset() {
	*x = ZRevRangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRevRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRevRangeResponse) ProtoMessage() {}

func (x *ZRevRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRevRangeResponse.ProtoReflect.Descriptor instead.
func (*ZRevRangeResponse) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{20}
}

func (x *ZRevRangeResponse) GetMembers() []*ZSetValue {
	if x != nil {
		return x.Members
	}
	return nil
}

type ZCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ZCardRequest) Reset() {
	*x = ZCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZCardRequest) ProtoMessage() {}

func (x *ZCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZCardRequest.ProtoReflect.Descriptor instead.
func (*ZCardRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{21}
}

func (x *ZCardRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ZCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ZCardResponse) Reset() {
	*x = ZCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZCardResponse) ProtoMessage() {}

func (x *ZCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZCardResponse.ProtoReflect.Descriptor instead.
func (*ZCardResponse) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{22}
}

func (x *ZCardResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ZIncrByRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Member string `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	IncBy  int32  `protobuf:"varint,3,opt,name=incBy,proto3" json:"incBy,omitempty"`
}

func (x *ZIncrByRequest) Reset() {
	*x = ZIncrByRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZIncrByRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZIncrByRequest) ProtoMessage() {}

func (x *ZIncrByRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZIncrByRequest.ProtoReflect.Descriptor instead.
func (*ZIncrByRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{23}
}

func (x *ZIncrByRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ZIncrByRequest) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *ZIncrByRequest) GetIncBy() int32 {
	if x != nil {
		return x.IncBy
	}
	return 0
}

type ZIncrByResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewScore int32 `protobuf:"varint,1,opt,name=newScore,proto3" json:"newScore,omitempty"`
	Exists   bool  `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *ZIncrByResponse) Reset() {
	*x = ZIncrByResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gzset_db_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZIncrByResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZIncrByResponse) ProtoMessage() {}

func (x *ZIncrByResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gzset_db_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZIncrByResponse.ProtoReflect.Descriptor instead.
func (*ZIncrByResponse) Descriptor() ([]byte, []int) {
	return file_lib_proto_gzset_db_proto_rawDescGZIP(), []int{24}
}

func (x *ZIncrByResponse) GetNewScore() int32 {
	if x != nil {
		return x.NewScore
	}
	return 0
}

func (x *ZIncrByResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_lib_proto_gzset_db_proto protoreflect.FileDescriptor

var file_lib_proto_gzset_db_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6c, 0x69, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x7a, 0x73, 0x65,
	0x74, 0x2f, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x7a, 0x73, 0x65,
	0x74, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a, 0x09,
	0x5a, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x49, 0x0a, 0x0b, 0x5a, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x7a, 0x73, 0x65, 0x74, 0x2e, 0x5a, 0x53, 0x65,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x42,
	0x0a, 0x0c, 0x5a, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x4c, 0x0a, 0x0c, 0x5a, 0x41, 0x64, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x7a, 0x73, 0x65, 0x74, 0x2e, 0x5a, 0x53,
	0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x22, 0x43, 0x0a, 0x0d, 0x5a, 0x41, 0x64, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x37, 0x0a, 0x0b, 0x5a, 0x52, 0x65, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x42,
	0x0a, 0x0c, 0x5a, 0x52, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x3a, 0x0a, 0x0c, 0x5a, 0x52, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x43,
	0x0a, 0x0d, 0x5a, 0x52, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x39, 0x0a, 0x0d, 0x5a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x3e,
	0x0a, 0x0e, 0x5a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x22, 0x38,
	0x0a, 0x0c, 0x5a, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x3b, 0x0a, 0x0d, 0x5a, 0x52, 0x61, 0x6e,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65,
	0x78, 0x69, 0x73, 0x74, 0x73, 0x22, 0x3b, 0x0a, 0x0f, 0x5a, 0x52, 0x65, 0x76, 0x52, 0x61, 0x6e,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0x3e, 0x0a, 0x10, 0x5a, 0x52, 0x65, 0x76, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78,
	0x69, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78, 0x69, 0x73,
	0x74, 0x73, 0x22, 0x49, 0x0a, 0x0d, 0x5a, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65,
	0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0x3c, 0x0a,
	0x0e, 0x5a, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2a, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x67, 0x7a, 0x73, 0x65, 0x74, 0x2e, 0x5a, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x45, 0x0a, 0x0d, 0x5a,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x69, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d,
	0x61, 0x78, 0x22, 0x26, 0x0a, 0x0e, 0x5a, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5c, 0x0a, 0x10, 0x5a, 0x52,
	0x65, 0x76, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x18,
	0x0a, 0x07, 0x65, 0x6e, 0x64, 0x52, 0x61, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x65, 0x6e, 0x64, 0x52, 0x61, 0x6e, 0x6b, 0x22, 0x3f, 0x0a, 0x11, 0x5a, 0x52, 0x65, 0x76,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a,
	0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x67, 0x7a, 0x73, 0x65, 0x74, 0x2e, 0x5a, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x20, 0x0a, 0x0c, 0x5a, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x25, 0x0a, 0x0d, 0x5a,
	0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x50, 0x0a, 0x0e, 0x5a, 0x49, 0x6e, 0x63, 0x72, 0x42, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x63, 0x42, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69,
	0x6e, 0x63, 0x42, 0x79, 0x22, 0x45, 0x0a, 0x0f, 0x5a, 0x49, 0x6e, 0x63, 0x72, 0x42, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x32, 0x9c, 0x05, 0x0a, 0x0c,
	0x47, 0x5a, 0x53, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x04,
	0x5a, 0x41, 0x64, 0x64, 0x12, 0x12, 0x2e, 0x67, 0x7a, 0x73, 0x65, 0x74, 0x2e, 0x5a, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x67, 0x7a, 0x73, 0x65, 0x74,
	0x2e, 0x5a, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a,
	0x05, 0x5a, 0x41, 0x64, 0x64, 0x73, 0x12, 0x13, 0x2e, 0x67, 0x7a, 0x73, 0x65, 0x74, 0x2e, 0x5a,
	0x41, 0x64, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x67, 0x7a,
	0x73, 0x65, 0x74, 0x2e, 0x5a, 0x41, 0x64, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2f, 0x0a, 0x04, 0x5a, 0x52, 0x65, 0x6d, 0x12, 0x12, 0x2e, 0x67, 0x7a, 0x73, 0x65,
	0x74, 0x2e, 0x5a, 0x52, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x67, 0x7a, 0x73, 0x65, 0x74, 0x2e, 0x5a, 0x52, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x5a, 0x52, 0x65, 0x6d, 0x73, 0x12, 0x13, 0x2e, 0x67, 0x7a,
	0x73, 0x65, 0x74, 0x2e, 0x5a, 0x52, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x67, 0x7a, 0x73, 0x65, 0x74, 0x2e, 0x5a, 0x52, 0x65, 0x6d, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x5a, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x12, 0x14, 0x2e, 0x67, 0x7a, 0x73, 0x65, 0x74, 0x2e, 0x5a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x67, 0x7a, 0x73, 0x65, 0x74, 0x2e, 0x5a,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a,
	0x05, 0x5a, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x13, 0x2e, 0x67, 0x7a, 0x73, 0x65, 0x74, 0x2e, 0x5a,
	0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x67, 0x7a,
	0x73, 0x65, 0x74, 0x2e, 0x5a, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3b, 0x0a, 0x08, 0x5a, 0x52, 0x65, 0x76, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x16, 0x2e,
	0x67, 0x7a, 0x73, 0x65, 0x74, 0x2e, 0x5a, 0x52, 0x65, 0x76, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x7a, 0x73, 0x65, 0x74, 0x2e, 0x5a, 0x52,
	0x65, 0x76, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35,
	0x0a, 0x06, 0x5a, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x14, 0x2e, 0x67, 0x7a, 0x73, 0x65, 0x74,
	0x2e, 0x5a, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x67, 0x7a, 0x73, 0x65, 0x74, 0x2e, 0x5a, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x5a, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x14, 0x2e, 0x67, 0x7a, 0x73, 0x65, 0x74, 0x2e, 0x5a, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x67, 0x7a, 0x73, 0x65, 0x74, 0x2e, 0x5a, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x09,
	0x5a, 0x52, 0x65, 0x76, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x17, 0x2e, 0x67, 0x7a, 0x73, 0x65,
	0x74, 0x2e, 0x5a, 0x52, 0x65, 0x76, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x7a, 0x73, 0x65, 0x74, 0x2e, 0x5a, 0x52, 0x65, 0x76, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x05,
	0x5a, 0x43, 0x61, 0x72, 0x64, 0x12, 0x13, 0x2e, 0x67, 0x7a, 0x73, 0x65, 0x74, 0x2e, 0x5a, 0x43,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x67, 0x7a, 0x73,
	0x65, 0x74, 0x2e, 0x5a, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x38, 0x0a, 0x07, 0x5a, 0x49, 0x6e, 0x63, 0x72, 0x42, 0x79, 0x12, 0x15, 0x2e, 0x67, 0x7a,
	0x73, 0x65, 0x74, 0x2e, 0x5a, 0x49, 0x6e, 0x63, 0x72, 0x42, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x7a, 0x73, 0x65, 0x74, 0x2e, 0x5a, 0x49, 0x6e, 0x63, 0x72,
	0x42, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x6c, 0x69,
	0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x7a, 0x73, 0x65, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lib_proto_gzset_db_proto_rawDescOnce sync.Once
	file_lib_proto_gzset_db_proto_rawDescData = file_lib_proto_gzset_db_proto_rawDesc
)

func file_lib_proto_gzset_db_proto_rawDescGZIP() []byte {
	file_lib_proto_gzset_db_proto_rawDescOnce.Do(func() {
		file_lib_proto_gzset_db_proto_rawDescData = protoimpl.X.CompressGZIP(file_lib_proto_gzset_db_proto_rawDescData)
	})
	return file_lib_proto_gzset_db_proto_rawDescData
}

var file_lib_proto_gzset_db_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_lib_proto_gzset_db_proto_goTypes = []interface{}{
	(*ZSetValue)(nil),         // 0: gzset.ZSetValue
	(*ZAddRequest)(nil),       // 1: gzset.ZAddRequest
	(*ZAddResponse)(nil),      // 2: gzset.ZAddResponse
	(*ZAddsRequest)(nil),      // 3: gzset.ZAddsRequest
	(*ZAddsResponse)(nil),     // 4: gzset.ZAddsResponse
	(*ZRemRequest)(nil),       // 5: gzset.ZRemRequest
	(*ZRemResponse)(nil),      // 6: gzset.ZRemResponse
	(*ZRemsRequest)(nil),      // 7: gzset.ZRemsRequest
	(*ZRemsResponse)(nil),     // 8: gzset.ZRemsResponse
	(*ZScoreRequest)(nil),     // 9: gzset.ZScoreRequest
	(*ZScoreResponse)(nil),    // 10: gzset.ZScoreResponse
	(*ZRankRequest)(nil),      // 11: gzset.ZRankRequest
	(*ZRankResponse)(nil),     // 12: gzset.ZRankResponse
	(*ZRevRankRequest)(nil),   // 13: gzset.ZRevRankRequest
	(*ZRevRankResponse)(nil),  // 14: gzset.ZRevRankResponse
	(*ZRangeRequest)(nil),     // 15: gzset.ZRangeRequest
	(*ZRangeResponse)(nil),    // 16: gzset.ZRangeResponse
	(*ZCountRequest)(nil),     // 17: gzset.ZCountRequest
	(*ZCountResponse)(nil),    // 18: gzset.ZCountResponse
	(*ZRevRangeRequest)(nil),  // 19: gzset.ZRevRangeRequest
	(*ZRevRangeResponse)(nil), // 20: gzset.ZRevRangeResponse
	(*ZCardRequest)(nil),      // 21: gzset.ZCardRequest
	(*ZCardResponse)(nil),     // 22: gzset.ZCardResponse
	(*ZIncrByRequest)(nil),    // 23: gzset.ZIncrByRequest
	(*ZIncrByResponse)(nil),   // 24: gzset.ZIncrByResponse
	(*any1.Any)(nil),          // 25: google.protobuf.Any
}
var file_lib_proto_gzset_db_proto_depIdxs = []int32{
	25, // 0: gzset.ZSetValue.value:type_name -> google.protobuf.Any
	0,  // 1: gzset.ZAddRequest.member:type_name -> gzset.ZSetValue
	0,  // 2: gzset.ZAddsRequest.members:type_name -> gzset.ZSetValue
	0,  // 3: gzset.ZRangeResponse.members:type_name -> gzset.ZSetValue
	0,  // 4: gzset.ZRevRangeResponse.members:type_name -> gzset.ZSetValue
	1,  // 5: gzset.GZSetService.ZAdd:input_type -> gzset.ZAddRequest
	3,  // 6: gzset.GZSetService.ZAdds:input_type -> gzset.ZAddsRequest
	5,  // 7: gzset.GZSetService.ZRem:input_type -> gzset.ZRemRequest
	7,  // 8: gzset.GZSetService.ZRems:input_type -> gzset.ZRemsRequest
	9,  // 9: gzset.GZSetService.ZScore:input_type -> gzset.ZScoreRequest
	11, // 10: gzset.GZSetService.ZRank:input_type -> gzset.ZRankRequest
	13, // 11: gzset.GZSetService.ZRevRank:input_type -> gzset.ZRevRankRequest
	15, // 12: gzset.GZSetService.ZRange:input_type -> gzset.ZRangeRequest
	17, // 13: gzset.GZSetService.ZCount:input_type -> gzset.ZCountRequest
	19, // 14: gzset.GZSetService.ZRevRange:input_type -> gzset.ZRevRangeRequest
	21, // 15: gzset.GZSetService.ZCard:input_type -> gzset.ZCardRequest
	23, // 16: gzset.GZSetService.ZIncrBy:input_type -> gzset.ZIncrByRequest
	2,  // 17: gzset.GZSetService.ZAdd:output_type -> gzset.ZAddResponse
	4,  // 18: gzset.GZSetService.ZAdds:output_type -> gzset.ZAddsResponse
	6,  // 19: gzset.GZSetService.ZRem:output_type -> gzset.ZRemResponse
	8,  // 20: gzset.GZSetService.ZRems:output_type -> gzset.ZRemsResponse
	10, // 21: gzset.GZSetService.ZScore:output_type -> gzset.ZScoreResponse
	12, // 22: gzset.GZSetService.ZRank:output_type -> gzset.ZRankResponse
	14, // 23: gzset.GZSetService.ZRevRank:output_type -> gzset.ZRevRankResponse
	16, // 24: gzset.GZSetService.ZRange:output_type -> gzset.ZRangeResponse
	18, // 25: gzset.GZSetService.ZCount:output_type -> gzset.ZCountResponse
	20, // 26: gzset.GZSetService.ZRevRange:output_type -> gzset.ZRevRangeResponse
	22, // 27: gzset.GZSetService.ZCard:output_type -> gzset.ZCardResponse
	24, // 28: gzset.GZSetService.ZIncrBy:output_type -> gzset.ZIncrByResponse
	17, // [17:29] is the sub-list for method output_type
	5,  // [5:17] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_lib_proto_gzset_db_proto_init() }
func file_lib_proto_gzset_db_proto_init() {
	if File_lib_proto_gzset_db_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lib_proto_gzset_db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZSetValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZAddsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZAddsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRemsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRemsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZScoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZScoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRankRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRankResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRevRankRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRevRankResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRevRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRevRangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZIncrByRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gzset_db_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZIncrByResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lib_proto_gzset_db_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lib_proto_gzset_db_proto_goTypes,
		DependencyIndexes: file_lib_proto_gzset_db_proto_depIdxs,
		MessageInfos:      file_lib_proto_gzset_db_proto_msgTypes,
	}.Build()
	File_lib_proto_gzset_db_proto = out.File
	file_lib_proto_gzset_db_proto_rawDesc = nil
	file_lib_proto_gzset_db_proto_goTypes = nil
	file_lib_proto_gzset_db_proto_depIdxs = nil
}
