apiVersion: v1
kind: Service
metadata:
  name: flydb-service
  namespace: flydb-system
spec:
  selector:
    app: flydb
  ports:
    - protocol: TCP
      port: 8999
      targetPort: 8999
  type: NodePort
