// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: lib/proto/gset/db.proto

package gset

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Member string `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *SAddRequest) Reset() {
	*x = SAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gset_db_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAddRequest) ProtoMessage() {}

func (x *SAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gset_db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAddRequest.ProtoReflect.Descriptor instead.
func (*SAddRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gset_db_proto_rawDescGZIP(), []int{0}
}

func (x *SAddRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SAddRequest) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

type SAddsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Members []string `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *SAddsRequest) Reset() {
	*x = SAddsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gset_db_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SAddsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAddsRequest) ProtoMessage() {}

func (x *SAddsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gset_db_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAddsRequest.ProtoReflect.Descriptor instead.
func (*SAddsRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gset_db_proto_rawDescGZIP(), []int{1}
}

func (x *SAddsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SAddsRequest) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type SRemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Member string `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *SRemRequest) Reset() {
	*x = SRemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gset_db_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SRemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRemRequest) ProtoMessage() {}

func (x *SRemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gset_db_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRemRequest.ProtoReflect.Descriptor instead.
func (*SRemRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gset_db_proto_rawDescGZIP(), []int{2}
}

func (x *SRemRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SRemRequest) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

type SRemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Members []string `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *SRemsRequest) Reset() {
	*x = SRemsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gset_db_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SRemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRemsRequest) ProtoMessage() {}

func (x *SRemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gset_db_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRemsRequest.ProtoReflect.Descriptor instead.
func (*SRemsRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gset_db_proto_rawDescGZIP(), []int{3}
}

func (x *SRemsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SRemsRequest) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type SCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *SCardRequest) Reset() {
	*x = SCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gset_db_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCardRequest) ProtoMessage() {}

func (x *SCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gset_db_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCardRequest.ProtoReflect.Descriptor instead.
func (*SCardRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gset_db_proto_rawDescGZIP(), []int{4}
}

func (x *SCardRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *SCardResponse) Reset() {
	*x = SCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gset_db_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCardResponse) ProtoMessage() {}

func (x *SCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gset_db_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCardResponse.ProtoReflect.Descriptor instead.
func (*SCardResponse) Descriptor() ([]byte, []int) {
	return file_lib_proto_gset_db_proto_rawDescGZIP(), []int{5}
}

func (x *SCardResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SMembersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *SMembersRequest) Reset() {
	*x = SMembersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gset_db_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMembersRequest) ProtoMessage() {}

func (x *SMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gset_db_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMembersRequest.ProtoReflect.Descriptor instead.
func (*SMembersRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gset_db_proto_rawDescGZIP(), []int{6}
}

func (x *SMembersRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members []string `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *SMembersResponse) Reset() {
	*x = SMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gset_db_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMembersResponse) ProtoMessage() {}

func (x *SMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gset_db_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMembersResponse.ProtoReflect.Descriptor instead.
func (*SMembersResponse) Descriptor() ([]byte, []int) {
	return file_lib_proto_gset_db_proto_rawDescGZIP(), []int{7}
}

func (x *SMembersResponse) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type SIsMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Member string `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *SIsMemberRequest) Reset() {
	*x = SIsMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gset_db_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SIsMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SIsMemberRequest) ProtoMessage() {}

func (x *SIsMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gset_db_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SIsMemberRequest.ProtoReflect.Descriptor instead.
func (*SIsMemberRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gset_db_proto_rawDescGZIP(), []int{8}
}

func (x *SIsMemberRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SIsMemberRequest) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

type SIsMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsMember bool `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
}

func (x *SIsMemberResponse) Reset() {
	*x = SIsMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gset_db_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SIsMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SIsMemberResponse) ProtoMessage() {}

func (x *SIsMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gset_db_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SIsMemberResponse.ProtoReflect.Descriptor instead.
func (*SIsMemberResponse) Descriptor() ([]byte, []int) {
	return file_lib_proto_gset_db_proto_rawDescGZIP(), []int{9}
}

func (x *SIsMemberResponse) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

type SUnionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *SUnionRequest) Reset() {
	*x = SUnionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gset_db_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SUnionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SUnionRequest) ProtoMessage() {}

func (x *SUnionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gset_db_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SUnionRequest.ProtoReflect.Descriptor instead.
func (*SUnionRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gset_db_proto_rawDescGZIP(), []int{10}
}

func (x *SUnionRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type SUnionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members []string `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *SUnionResponse) Reset() {
	*x = SUnionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gset_db_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SUnionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SUnionResponse) ProtoMessage() {}

func (x *SUnionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gset_db_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SUnionResponse.ProtoReflect.Descriptor instead.
func (*SUnionResponse) Descriptor() ([]byte, []int) {
	return file_lib_proto_gset_db_proto_rawDescGZIP(), []int{11}
}

func (x *SUnionResponse) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type SInterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *SInterRequest) Reset() {
	*x = SInterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gset_db_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SInterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SInterRequest) ProtoMessage() {}

func (x *SInterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gset_db_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SInterRequest.ProtoReflect.Descriptor instead.
func (*SInterRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gset_db_proto_rawDescGZIP(), []int{12}
}

func (x *SInterRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type SInterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members []string `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *SInterResponse) Reset() {
	*x = SInterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gset_db_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SInterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SInterResponse) ProtoMessage() {}

func (x *SInterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gset_db_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SInterResponse.ProtoReflect.Descriptor instead.
func (*SInterResponse) Descriptor() ([]byte, []int) {
	return file_lib_proto_gset_db_proto_rawDescGZIP(), []int{13}
}

func (x *SInterResponse) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type SDiffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *SDiffRequest) Reset() {
	*x = SDiffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gset_db_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SDiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SDiffRequest) ProtoMessage() {}

func (x *SDiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gset_db_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SDiffRequest.ProtoReflect.Descriptor instead.
func (*SDiffRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gset_db_proto_rawDescGZIP(), []int{14}
}

func (x *SDiffRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type SDiffResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members []string `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *SDiffResponse) Reset() {
	*x = SDiffResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gset_db_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SDiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SDiffResponse) ProtoMessage() {}

func (x *SDiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gset_db_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SDiffResponse.ProtoReflect.Descriptor instead.
func (*SDiffResponse) Descriptor() ([]byte, []int) {
	return file_lib_proto_gset_db_proto_rawDescGZIP(), []int{15}
}

func (x *SDiffResponse) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type SUnionStoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Destination string   `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Keys        []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *SUnionStoreRequest) Reset() {
	*x = SUnionStoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gset_db_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SUnionStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SUnionStoreRequest) ProtoMessage() {}

func (x *SUnionStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gset_db_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SUnionStoreRequest.ProtoReflect.Descriptor instead.
func (*SUnionStoreRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gset_db_proto_rawDescGZIP(), []int{16}
}

func (x *SUnionStoreRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *SUnionStoreRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type SInterStoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Destination string   `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Keys        []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *SInterStoreRequest) Reset() {
	*x = SInterStoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gset_db_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SInterStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SInterStoreRequest) ProtoMessage() {}

func (x *SInterStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gset_db_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SInterStoreRequest.ProtoReflect.Descriptor instead.
func (*SInterStoreRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_gset_db_proto_rawDescGZIP(), []int{17}
}

func (x *SInterStoreRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *SInterStoreRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type EmptyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_gset_db_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_gset_db_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_lib_proto_gset_db_proto_rawDescGZIP(), []int{18}
}

var File_lib_proto_gset_db_proto protoreflect.FileDescriptor

var file_lib_proto_gset_db_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6c, 0x69, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x73, 0x65, 0x74,
	0x2f, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x73, 0x65, 0x74, 0x22,
	0x37, 0x0a, 0x0b, 0x53, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x3a, 0x0a, 0x0c, 0x53, 0x41, 0x64, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x22, 0x37, 0x0a, 0x0b, 0x53, 0x52, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x3a, 0x0a,
	0x0c, 0x53, 0x52, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x20, 0x0a, 0x0c, 0x53, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x25, 0x0a, 0x0d, 0x53,
	0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x23, 0x0a, 0x0f, 0x53, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x2c, 0x0a, 0x10, 0x53, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x3c, 0x0a, 0x10, 0x53, 0x49, 0x73, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x22, 0x30, 0x0a, 0x11, 0x53, 0x49, 0x73, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x23, 0x0a, 0x0d, 0x53, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x2a, 0x0a, 0x0e, 0x53, 0x55,
	0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x23, 0x0a, 0x0d, 0x53, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x2a, 0x0a, 0x0e, 0x53,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x22, 0x0a, 0x0c, 0x53, 0x44, 0x69, 0x66, 0x66,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x29, 0x0a, 0x0d, 0x53,
	0x44, 0x69, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x4a, 0x0a, 0x12, 0x53, 0x55, 0x6e, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65,
	0x79, 0x73, 0x22, 0x4a, 0x0a, 0x12, 0x53, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65,
	0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x0f,
	0x0a, 0x0d, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0x94, 0x05, 0x0a, 0x0b, 0x47, 0x53, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x2e, 0x0a, 0x04, 0x53, 0x41, 0x64, 0x64, 0x12, 0x11, 0x2e, 0x67, 0x73, 0x65, 0x74, 0x2e, 0x53,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x67, 0x73, 0x65,
	0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x30, 0x0a, 0x05, 0x53, 0x41, 0x64, 0x64, 0x73, 0x12, 0x12, 0x2e, 0x67, 0x73, 0x65, 0x74, 0x2e,
	0x53, 0x41, 0x64, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x67,
	0x73, 0x65, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2e, 0x0a, 0x04, 0x53, 0x52, 0x65, 0x6d, 0x12, 0x11, 0x2e, 0x67, 0x73, 0x65, 0x74,
	0x2e, 0x53, 0x52, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x67,
	0x73, 0x65, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x30, 0x0a, 0x05, 0x53, 0x52, 0x65, 0x6d, 0x73, 0x12, 0x12, 0x2e, 0x67, 0x73, 0x65,
	0x74, 0x2e, 0x53, 0x52, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x67, 0x73, 0x65, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x53, 0x43, 0x61, 0x72, 0x64, 0x12, 0x12, 0x2e, 0x67,
	0x73, 0x65, 0x74, 0x2e, 0x53, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x67, 0x73, 0x65, 0x74, 0x2e, 0x53, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x53, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x12, 0x15, 0x2e, 0x67, 0x73, 0x65, 0x74, 0x2e, 0x53, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x73, 0x65, 0x74, 0x2e,
	0x53, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3c, 0x0a, 0x09, 0x53, 0x49, 0x73, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x2e,
	0x67, 0x73, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x73, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x73, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x73,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33,
	0x0a, 0x06, 0x53, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x13, 0x2e, 0x67, 0x73, 0x65, 0x74, 0x2e,
	0x53, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x67, 0x73, 0x65, 0x74, 0x2e, 0x53, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x53, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x13, 0x2e,
	0x67, 0x73, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x67, 0x73, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x53, 0x44, 0x69, 0x66,
	0x66, 0x12, 0x12, 0x2e, 0x67, 0x73, 0x65, 0x74, 0x2e, 0x53, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x67, 0x73, 0x65, 0x74, 0x2e, 0x53, 0x44, 0x69,
	0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x53, 0x55,
	0x6e, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x18, 0x2e, 0x67, 0x73, 0x65, 0x74,
	0x2e, 0x53, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x67, 0x73, 0x65, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x53, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x18, 0x2e, 0x67, 0x73, 0x65, 0x74, 0x2e, 0x53,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x67, 0x73, 0x65, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x6c, 0x69, 0x62, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x73, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lib_proto_gset_db_proto_rawDescOnce sync.Once
	file_lib_proto_gset_db_proto_rawDescData = file_lib_proto_gset_db_proto_rawDesc
)

func file_lib_proto_gset_db_proto_rawDescGZIP() []byte {
	file_lib_proto_gset_db_proto_rawDescOnce.Do(func() {
		file_lib_proto_gset_db_proto_rawDescData = protoimpl.X.CompressGZIP(file_lib_proto_gset_db_proto_rawDescData)
	})
	return file_lib_proto_gset_db_proto_rawDescData
}

var file_lib_proto_gset_db_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_lib_proto_gset_db_proto_goTypes = []interface{}{
	(*SAddRequest)(nil),        // 0: gset.SAddRequest
	(*SAddsRequest)(nil),       // 1: gset.SAddsRequest
	(*SRemRequest)(nil),        // 2: gset.SRemRequest
	(*SRemsRequest)(nil),       // 3: gset.SRemsRequest
	(*SCardRequest)(nil),       // 4: gset.SCardRequest
	(*SCardResponse)(nil),      // 5: gset.SCardResponse
	(*SMembersRequest)(nil),    // 6: gset.SMembersRequest
	(*SMembersResponse)(nil),   // 7: gset.SMembersResponse
	(*SIsMemberRequest)(nil),   // 8: gset.SIsMemberRequest
	(*SIsMemberResponse)(nil),  // 9: gset.SIsMemberResponse
	(*SUnionRequest)(nil),      // 10: gset.SUnionRequest
	(*SUnionResponse)(nil),     // 11: gset.SUnionResponse
	(*SInterRequest)(nil),      // 12: gset.SInterRequest
	(*SInterResponse)(nil),     // 13: gset.SInterResponse
	(*SDiffRequest)(nil),       // 14: gset.SDiffRequest
	(*SDiffResponse)(nil),      // 15: gset.SDiffResponse
	(*SUnionStoreRequest)(nil), // 16: gset.SUnionStoreRequest
	(*SInterStoreRequest)(nil), // 17: gset.SInterStoreRequest
	(*EmptyResponse)(nil),      // 18: gset.EmptyResponse
}
var file_lib_proto_gset_db_proto_depIdxs = []int32{
	0,  // 0: gset.GSetService.SAdd:input_type -> gset.SAddRequest
	1,  // 1: gset.GSetService.SAdds:input_type -> gset.SAddsRequest
	2,  // 2: gset.GSetService.SRem:input_type -> gset.SRemRequest
	3,  // 3: gset.GSetService.SRems:input_type -> gset.SRemsRequest
	4,  // 4: gset.GSetService.SCard:input_type -> gset.SCardRequest
	6,  // 5: gset.GSetService.SMembers:input_type -> gset.SMembersRequest
	8,  // 6: gset.GSetService.SIsMember:input_type -> gset.SIsMemberRequest
	10, // 7: gset.GSetService.SUnion:input_type -> gset.SUnionRequest
	12, // 8: gset.GSetService.SInter:input_type -> gset.SInterRequest
	14, // 9: gset.GSetService.SDiff:input_type -> gset.SDiffRequest
	16, // 10: gset.GSetService.SUnionStore:input_type -> gset.SUnionStoreRequest
	17, // 11: gset.GSetService.SInterStore:input_type -> gset.SInterStoreRequest
	18, // 12: gset.GSetService.SAdd:output_type -> gset.EmptyResponse
	18, // 13: gset.GSetService.SAdds:output_type -> gset.EmptyResponse
	18, // 14: gset.GSetService.SRem:output_type -> gset.EmptyResponse
	18, // 15: gset.GSetService.SRems:output_type -> gset.EmptyResponse
	5,  // 16: gset.GSetService.SCard:output_type -> gset.SCardResponse
	7,  // 17: gset.GSetService.SMembers:output_type -> gset.SMembersResponse
	9,  // 18: gset.GSetService.SIsMember:output_type -> gset.SIsMemberResponse
	11, // 19: gset.GSetService.SUnion:output_type -> gset.SUnionResponse
	13, // 20: gset.GSetService.SInter:output_type -> gset.SInterResponse
	15, // 21: gset.GSetService.SDiff:output_type -> gset.SDiffResponse
	18, // 22: gset.GSetService.SUnionStore:output_type -> gset.EmptyResponse
	18, // 23: gset.GSetService.SInterStore:output_type -> gset.EmptyResponse
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_lib_proto_gset_db_proto_init() }
func file_lib_proto_gset_db_proto_init() {
	if File_lib_proto_gset_db_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lib_proto_gset_db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gset_db_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SAddsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gset_db_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SRemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gset_db_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SRemsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gset_db_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gset_db_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gset_db_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMembersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gset_db_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gset_db_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SIsMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gset_db_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SIsMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gset_db_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SUnionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gset_db_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SUnionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gset_db_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SInterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gset_db_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SInterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gset_db_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SDiffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gset_db_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SDiffResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gset_db_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SUnionStoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gset_db_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SInterStoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_gset_db_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lib_proto_gset_db_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lib_proto_gset_db_proto_goTypes,
		DependencyIndexes: file_lib_proto_gset_db_proto_depIdxs,
		MessageInfos:      file_lib_proto_gset_db_proto_msgTypes,
	}.Build()
	File_lib_proto_gset_db_proto = out.File
	file_lib_proto_gset_db_proto_rawDesc = nil
	file_lib_proto_gset_db_proto_goTypes = nil
	file_lib_proto_gset_db_proto_depIdxs = nil
}
