# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ "1.18", "1.19", "1.20" ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install Dependency
        run: sudo apt-get update && sudo apt-get -y install librocksdb-dev

      - name: Check Format
        run: |
          unformatted=$(gofmt -s -l .)
          if [ "$unformatted" != "" ]; then
            echo "the following files are not formatted:"
            for file in $unformatted; do
              echo "$file:"
              gofmt -s -d "$file"
              echo "------"
            done
            exit 1
          fi



      - name: Lint
        uses: golangci/golangci-lint-action@v3.6.0
        with:
          args: --verbose
          version: v1.53

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go list ./... | grep -v "./cmd/client" | xargs go test -v

  IntegrationTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Hash Structure Integration test
        run: go test -v -a -tags hash_integration ./cmd/client/...

      - name: List Structure Integration test
        run: go test -v -a -tags list_integration ./cmd/client/...

      - name: Set Structure Integration test
        run: go test -v -a -tags set_integration ./cmd/client/...

      - name: String Structure Integration test
        run: go test -v -a -tags string_integration ./cmd/client/...

      - name: ZSet Structure Integration test
        run: go test -v -a -tags zset_integration ./cmd/client/...